databases:
  - name: smell-the-roses
    databaseName: smell_the_roses_prod
    user: matt

services:
  - type: web
    name: smell-the-roses
    runtime: ruby
    buildCommand: './bin/render-build.sh'
    startCommand: 'bundle exec puma -C config/puma.rb'
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: smell-the-roses
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false
